---
HOSTS:
  windefault:
    roles:
      - default
      - windows
    platform: windows-server-amd64
    box: gusztavvargadr/windows-server
    box_version: '~> 2102'
    hypervisor: <%= ENV['BEAKER_HYPERVISOR'] || 'vagrant' %>
    vagrant_memsize: 2048
    vagrant_cpus: 2
    user: vagrant
    is_cygwin: false

CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] || 'puppet7' %>
